import pymongo
conn = pymongo.MongoClient("mongodb://localhost:27017/")
mydb = conn["Data"]
mycol = mydb["Appcode"]
mycol = mydb["Answerq1"]
mycol = mydb["Answerq2"]
mycol = mydb["Answerq3"]
mycol = mydb["Answerq4"]
mycol = mydb["Answerq5"]
mycol = mydb["Answerq6"]
mycol = mydb["Answerq7"]
mycol = mydb["Answerq8"]
mycol = mydb["Answerq9"]
mycol = mydb["Answerq10"]
mycol = mydb["Answerq11"]
mycol = mydb["Answerq12"]
mycol = mydb["Answerq13"]
mycol = mydb["Answerq14"]
mycol = mydb["Answerq15"]
mycol = mydb["Answerq16"]
mycol = mydb["Answerq17"]
mycol = mydb["Answerq18"]
mycol = mydb["Answerq19"]
mycol = mydb["Answerq20"]
print("Done Successfully..!")
